### ISSUE TITLE
Lucy ore by Mine Level Configuration Support

### ISSUE THREAD

**Issue by efinder2** [ldtteam/minecolonies-features#784]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.(and Read the source on master branch)
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version: 1.19
- MineColonies Version: Git tag 015eeeb (current master)
- Related Mods and their Versions: -

## Is your feature request related to a problem?

Currently I'm evaluating to create an expert Mod Pack on the back of minecolonies. I'd love to modify the lucky ore chance by the mine level.

## Enhancement or Change description

I prupose an extension of the config. If present the folowing should be interpreted:

```toml
[gameplay]
        # ...
	#Chance to get a lucky block in percent. [Default: 1]
	#Range: 0 ~ 100
	luckyblockchance = 1
        #Overrides when present the luckyblockchance property for miners on the corresponding level
        luckyblockchanceLevel1 = 1
        luckyblockchanceLevel2 = 1
        luckyblockchanceLevel3 = 2
        luckyblockchanceLevel4 = 2
        luckyblockchanceLevel4 = 3
        #..
[compatibility]
     # ....
     #Overrides when present the luckyores property for miners on Level 1
     luckyoresLevel1 = ["minecraft:coal_ore!64", "minecraft:iron_ore!32"]
     #Overrides when present the luckyores property for miners on Level 2
     luckyoresLevel2 = ["minecraft:coal_ore!64", "minecraft:iron_ore!32", "minecraft:gold_ore!16"]
    # continue with level 3-5
    # ....
```

### Notes or related things

If accepted I'd could try to implement it my self. 
---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.
