### ISSUE TITLE
Allow the chuck claim radius to be configurable

### ISSUE THREAD

**Issue by taylor-scafe** [ldtteam/minecolonies-features#901]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version: 1.21.1
- MineColonies Version: 1.1.921
- Related Mods and their Versions:

## Enhancement or Change description
Allow the chuck claim radius be configurable. A list per building type with the radius per level

```toml
#All configuration related to colony claims
[claims]
  #minecolonies.config.townhallClaimRadius.comment [Default: [1,1,2,3,5]]
  # Radius per level
  # Default: [1,1,2,3,5]
  townhallClaimRadius = [1,1,2,3,5]
  #minecolonies.config.guardtowerClaimRadius.comment [Default: [2,3,3,4,5]]
  # Radius per level
  # Default: [2,3,3,4,5]
  guardtowerClaimRadius = [2,3,3,4,5]
  #minecolonies.config.barracksClaimRadius.comment [Default: [2,2,2,2,2]]
  # Radius per level
  # Default: [2,2,2,2,2]
  barracksClaimRadius = [2,2,2,2,2]
  #minecolonies.config.otherClaimRadius.comment [Default: [1,1,1,2,2]]
  # Radius per level
  # Default: [1,1,1,2,2]
  otherClaimRadius = [1,1,1,2,2]
```

### Notes or related things
This will allow for worlds to have rapidly expanding colonies at the cost of efficiency due to colonist travel time

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.
